//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email()
        {
            this.Email1 = new HashSet<Email>();
            this.Employee_has_Email = new HashSet<Employee_has_Email>();
        }
    
        public int EmailId { get; set; }
        public int EmpId { get; set; }
        public string E_Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsPublicEmail { get; set; }
        public Nullable<bool> IsGroupEmail { get; set; }
        public Nullable<bool> IsPrivateEmail { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string sentToList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Email1 { get; set; }
        public virtual Email Email2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_has_Email> Employee_has_Email { get; set; }
    }
}
