//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_In_Group = new HashSet<Employee_In_Group>();
            this.Employee_has_Email = new HashSet<Employee_has_Email>();
        }
    
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public string EmpHash { get; set; }
        public string OrgCode { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> loginStatus { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> InGroup { get; set; }
        public Nullable<bool> IsGroupManager { get; set; }
        public Nullable<bool> IsOrgManager { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> DepId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_In_Group> Employee_In_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_has_Email> Employee_has_Email { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
