//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_has_Email
    {
        public int EmpId { get; set; }
        public int EmailId { get; set; }
        public Nullable<bool> IsStarred { get; set; }
        public Nullable<bool> IsSnoozed { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<bool> IsSpam { get; set; }
        public Nullable<bool> IsSeen { get; set; }
        public Nullable<bool> WasDeleted { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
