//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Employees = new HashSet<Employee>();
            this.Organization_has_Partner = new HashSet<Organization_has_Partner>();
            this.Organization_has_Partner1 = new HashSet<Organization_has_Partner>();
        }
    
        public int OrgId { get; set; }
        public string OrgName { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public string Vision_Statement { get; set; }
        public string OrgType { get; set; }
        public Nullable<bool> HasOrgCode { get; set; }
        public string Manager_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization_has_Partner> Organization_has_Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization_has_Partner> Organization_has_Partner1 { get; set; }
    }
}
