//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization_has_Partner
    {
        public int PartnerId { get; set; }
        public int OrgId { get; set; }
        public string SharedVision { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
    }
}
